[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
via_ir = true
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false
always_use_create_2_factory = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "solady/=lib/solady/src/",
  ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
